# Generated by Django 4.1.1 on 2022-09-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_dailyrecord_habit_target_habit_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit_tracker.habit'),
        ),
    ]
