# Generated by Django 4.1.1 on 2022-09-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_remove_dailyrecord_date_remove_habit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='target_completed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit_tracker.habit'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_constraint'),
        ),
    ]
